USE CALIFREPORTINGDB_H2O;

SHOW TABLES;


SELECT * FROM TUBBSING_TREE_MORTALITY LIMIT 50;

SELECT M.CARDBRECID, BURN.BURNSEVERITY2020BA4, M.LEMMA_CODE, GEO.LON, GEO.LAT, GEO.GEO_SHP, EVT140.EVT_FUEL_N
FROM public.MASTER021920 AS M 
JOIN public.BURNSEVERITY2020 AS BURN ON BURN.CARDBRECID = M.CARDBRECID
JOIN public.GEO_LAT_LON AS GEO ON GEO.CARDBRECID = M.CARDBRECID
JOIN public.CA_EVT140 AS EVT140 ON EVT140.VALUE = M.EVT140
WHERE BURN.BURNSEVERITY2020BA4 <=4
LIMIT 100





USE DEMO_DB;
SHOW TABLES;

SELECT * FROM TEST_TB;
INSERT INTO TEST_TB VALUES(1, 'FRANK');


USE DATABASE CALIFREPORTINGDB_H2O;

CREATE TABLE DEMO_DB.PUBLIC.FIRE_SEVERITY AS
(SELECT M.CARDBRECID, BURN.BURNSEVERITY2020BA4, M.LEMMA_CODE, GEO.LON, GEO.LAT, GEO.GEO_SHP, EVT140.EVT_FUEL_N,E.SLOPE, E.ELEV_M, E.ASPECT, 'Creek'AS FIRE_NAME
FROM public.MASTER021920 AS M 
JOIN public.BURNSEVERITY2020 AS BURN ON BURN.CARDBRECID = M.CARDBRECID
JOIN public.GEO_LAT_LON AS GEO ON GEO.CARDBRECID = M.CARDBRECID
JOIN public.CA_EVT140 AS EVT140 ON EVT140.VALUE = M.EVT140
JOIN public.ELEV AS E ON E.CARDBRECID = M.CARDBRECID
JOIN public.TUBBSING_TREE_MORTALITY TM on TM.CARDBRECID = BURN.CARDBRECID
WHERE BURN.BURNSEVERITY2020BA4 <=4
AND LON BETWEEN -119.63 AND -118.79
AND LAT BETWEEN 36.93 AND 37.718
UNION 
SELECT M.CARDBRECID, BURN.BURNSEVERITY2020BA4, M.LEMMA_CODE, GEO.LON, GEO.LAT, GEO.GEO_SHP, EVT140.EVT_FUEL_N,E.SLOPE, E.ELEV_M, E.ASPECT, 'Claremont-Bear'AS FIRE_NAME
FROM public.MASTER021920 AS M 
JOIN public.BURNSEVERITY2020 AS BURN ON BURN.CARDBRECID = M.CARDBRECID
JOIN public.GEO_LAT_LON AS GEO ON GEO.CARDBRECID = M.CARDBRECID
JOIN public.CA_EVT140 AS EVT140 ON EVT140.VALUE = M.EVT140
JOIN public.ELEV AS E ON E.CARDBRECID = M.CARDBRECID
JOIN public.TUBBSING_TREE_MORTALITY TM on TM.CARDBRECID = BURN.CARDBRECID
WHERE BURN.BURNSEVERITY2020BA4 <=4
AND LON BETWEEN -121.336 AND -120.74
AND LAT BETWEEN 39.522 AND 39.91
UNION 
SELECT M.CARDBRECID, BURN.BURNSEVERITY2020BA4, M.LEMMA_CODE, GEO.LON, GEO.LAT, GEO.GEO_SHP, EVT140.EVT_FUEL_N,E.SLOPE, E.ELEV_M, E.ASPECT,  'Castle'AS FIRE_NAME
FROM public.MASTER021920 AS M 
JOIN public.BURNSEVERITY2020 AS BURN ON BURN.CARDBRECID = M.CARDBRECID
JOIN public.GEO_LAT_LON AS GEO ON GEO.CARDBRECID = M.CARDBRECID
JOIN public.CA_EVT140 AS EVT140 ON EVT140.VALUE = M.EVT140
JOIN public.ELEV AS E ON E.CARDBRECID = M.CARDBRECID
JOIN public.TUBBSING_TREE_MORTALITY TM on TM.CARDBRECID = BURN.CARDBRECID
WHERE BURN.BURNSEVERITY2020BA4 <=4
AND LON BETWEEN -118.833 AND -118.256
AND LAT BETWEEN 36.082 AND 36.397);

USE DEMO_DB;











SELECT * FROM PUBLIC.FIRE_SEVERITY AS M
//
//df = cur.fetch_pandas_all()
//df
//

SELECT * 
FROM PUBLIC.FIRE_SEVERITY AS M 
WHERE FIRE_NAME = 'Castle';
//
//df_castle = cur.fetch_pandas_all()
//df_castle


SELECT *
FROM PUBLIC.DW_SEVERITY AS M 
WHERE FIRE_NAME = 'Claremont-Bear'


//cur.execute(sql)
//df_claremont = cur.fetch_pandas_all()
//df_claremont

SELECT *
FROM PUBLIC.DW_SEVERITY AS M 
WHERE FIRE_NAME = 'Creek'

//cur.execute(sql)
//df_creek = cur.fetch_pandas_all()
//df_creek



SELECT BURNSEVERITY2020BA4, LEMMA_CODE, LON, LAT, SLOPE, ELEV_M, ASPECT
FROM PUBLIC.FIRE_SEVERITY

//cur.execute(sql)
//df_regression = cur.fetch_pandas_all()
//df_regression
//